/** Tiny POS v3.6 searchable sale list. */
function getSalesList(sessionToken, filters) {
  const user=requireSession_(sessionToken);requirePermission_(user,'SALES_LIST');filters=filters||{};
  const range=reportRange_(filters.from,filters.to),query=sanitizeText_(filters.query,160).toLowerCase(),method=sanitizeText_(filters.method,30).toUpperCase(),status=sanitizeText_(filters.status,40).toUpperCase(),branchId=sanitizeText_(filters.branchId,80);
  const payments=getRows_(POS.SHEETS.PAYMENTS),paidBySale={};
  payments.forEach(function(payment){const id=String(payment.SaleID),currency=String(payment.Currency||'USD').toUpperCase(),sale=findRowBy_(POS.SHEETS.SALES,'SaleID',id),rate=sale?number_(sale.ExchangeRate,4100):4100;const usd=currency==='KHR'?number_(payment.Amount)/rate:number_(payment.Amount);paidBySale[id]=roundMoney_(number_(paidBySale[id])+usd);});
  const rows=getRows_(POS.SHEETS.SALES).filter(function(sale){const d=reportDate_(sale.DateTime||sale.CreatedAt);if(!d||d<range.from||d>range.to)return false;if(method&&String(sale.PaymentMethod||'').toUpperCase().indexOf(method)<0)return false;if(status&&String(sale.Status||'').toUpperCase()!==status)return false;if(branchId&&String(sale.BranchID||BRANCH_FEATURE.DEFAULT_BRANCH_ID)!==branchId)return false;const hay=[sale.InvoiceNo,sale.CustomerName,sale.CustomerType,sale.CashierName,sale.PaymentMethod,sale.PaymentStatus,sale.Status].join(' ').toLowerCase();return !query||hay.indexOf(query)>=0;}).sort(function(a,b){return new Date(b.DateTime||b.CreatedAt)-new Date(a.DateTime||a.CreatedAt);}).slice(0,1000).map(function(sale){const paid=paidBySale[String(sale.SaleID)]!==undefined?paidBySale[String(sale.SaleID)]:number_(sale.AmountPaidUSD);return {saleId:String(sale.SaleID),invoiceNo:String(sale.InvoiceNo),dateTime:new Date(sale.DateTime||sale.CreatedAt).toISOString(),customerName:String(sale.CustomerName||'Walk-in customer'),customerType:String(sale.CustomerType||'WALK-IN'),amountUSD:number_(sale.TotalUSD),paidUSD:roundMoney_(paid),creditUSD:number_(sale.CreditAmountUSD),method:String(sale.PaymentMethod||''),paymentStatus:String(sale.PaymentStatus||''),status:String(sale.Status||''),cashierName:String(sale.CashierName||''),branchId:String(sale.BranchID||BRANCH_FEATURE.DEFAULT_BRANCH_ID),pendingNo:String(sale.PendingNo||'')};});
  return {rows:rows,metrics:{sales:rows.length,totalUSD:roundMoney_(rows.reduce(function(s,r){return s+r.amountUSD;},0)),paidUSD:roundMoney_(rows.reduce(function(s,r){return s+r.paidUSD;},0)),creditUSD:roundMoney_(rows.reduce(function(s,r){return s+r.creditUSD;},0))},branches:listBranchesForUserManagement_(user)};
}
